// <auto-generated />
using System;
using MicroGestionale.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MicroGestionale.Migrations
{
    [DbContext(typeof(GestionaleDbContext))]
    [Migration("20260912204653_CreazioneIniziale")]
    partial class CreazioneIniziale
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.31");

            modelBuilder.Entity("MicroGestionale.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Bloccato")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cap")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Citta")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CodiceFiscale")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Indirizzo")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nazione")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("PartitaIva")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provincia")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clienti");
                });

            modelBuilder.Entity("MicroGestionale.Models.Preventivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ValidoFinoAl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Preventivi");
                });

            modelBuilder.Entity("MicroGestionale.Models.RigaPreventivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AliquotaIva")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Posizione")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PreventivoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrezzoUnitario")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantita")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ScontoPercentuale")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PreventivoId");

                    b.ToTable("RighePreventivo");
                });

            modelBuilder.Entity("MicroGestionale.Models.Preventivo", b =>
                {
                    b.HasOne("MicroGestionale.Models.Cliente", "Cliente")
                        .WithMany("Preventivi")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("MicroGestionale.Models.RigaPreventivo", b =>
                {
                    b.HasOne("MicroGestionale.Models.Preventivo", "Preventivo")
                        .WithMany("Righe")
                        .HasForeignKey("PreventivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Preventivo");
                });

            modelBuilder.Entity("MicroGestionale.Models.Cliente", b =>
                {
                    b.Navigation("Preventivi");
                });

            modelBuilder.Entity("MicroGestionale.Models.Preventivo", b =>
                {
                    b.Navigation("Righe");
                });
#pragma warning restore 612, 618
        }
    }
}
